name: Publish

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  klever-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
      - name: setup env
        run: |
          echo "RELEASE_VERSION=$(git describe --tags)" >> $GITHUB_ENV
      - name: docker-build
        run: |
          docker build -t ghcr.io/kleveross/klever-web:$RELEASE_VERSION -f Dockerfile .
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      - name: docker-push
        run: |
          docker push ghcr.io/kleveross/klever-web:$RELEASE_VERSION
